easy_admin:
    entities:
        # List the entity class name you want to manage
        - App\Entity\Productos
        - App\Entity\Categorias
        - App\Entity\Usuarios
        - App\Entity\ProductosUsuarios
